# Generated by Django 6.0.1 on 2026-01-14 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='director',
            field=models.CharField(default='N/A', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='lead_actor',
            field=models.CharField(default='N/A', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='lead_actress',
            field=models.CharField(default='N/A', max_length=150),
            preserve_default=False,
        ),
    ]
