# Generated by Django 6.0.1 on 2026-01-14 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_movie_director_movie_lead_actor_movie_lead_actress'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='ja_assisti',
            field=models.CharField(default='N/A', max_length=150),
            preserve_default=False,
        ),
    ]
