# Generated by Django 6.0.1 on 2026-01-15 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_movie_ja_assisti'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='ja_assisti',
        ),
        migrations.AddField(
            model_name='movie',
            name='is_watched',
            field=models.BooleanField(default=False),
        ),
    ]
